#!/bin/bash

export LANG=C
export LC_ALL=C

type -p debsums >/dev/null 2>&1
if test "x$?" = "x1"
then
	echo "Please install debsums" >&2
	echo "apt-get intall debsums" >&2
	exit 2
fi

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

IGNORE_PATTERN="ignore.d/"

if test -f ${SCRIPTPATH}/config.sh
then
	source ${SCRIPTPATH}/config.sh
fi

(
	for IP in ${IGNORE_PATTERN}
	do
		cat ${SCRIPTPATH}/${IP}*.ignore
		md5sum -c ${SCRIPTPATH}/${IP}*.ignore-chk | grep 'OK$' | sed -e 's/:  *OK *$//'
	done

	echo
	echo "# from debsums"
	debsums -e | grep 'OK$' | sed -e 's/  *OK *$//'


	echo
	echo "# symlinks"
	find	\
		/etc/ssl \
		/etc/fonts \
		/etc/apache2/mods-enabled \
		/etc/php/7.0/apache2/conf.d \
		/etc/php/7.0/cli/conf.d \
		/etc/php5/apache2/conf.d \
		/etc/php5/cli/conf.d \
		-type l

) >/.git/info/exclude 2>/dev/null

