#!/bin/bash

FILE_INIT_COMMANDS=/etc/sysgit/initcommand.sh
RUNFILE=/var/run/sysgit-run-commands

if test "x$1" = "xcheckout" || test "x$1" = "xmerge"
then
	if test -f "${RUNFILE}" &&
		test "${RUNFILE}" -nt "${FILE_INIT_COMMANDS}"
	then
		exit 1
	fi
	touch "${RUNFILE}"
fi

exec "${FILE_INIT_COMMANDS}" "$@"

